# SPDX-FileCopyrightText: 2026 M5Stack Technology CO LTD
# SPDX-License-Identifier: MIT

import os
import shutil
import shlex
import subprocess
from pathlib import Path
Import("env")
with open(env["PROJECT_TOOL_S"]) as f:
    exec(f.read())

if "CONFIG_TOOLCHAIN_PREFIX" in os.environ:
    env["RANLIB"] = '${_concat(GCCPREFIX, "ranlib", GCCSUFFIX, __env__)}'
    env["RANLIBCOM"] = "$RANLIB $TARGET"
    env["ARFLAGS"] = ["rcs"]

SRCS = Glob("src/*.c*")
SRCS += append_srcs_dir(ADir("backend"))
SRCS += append_srcs_dir(ADir("interface"))
SRCS += append_srcs_dir(ADir("ui"))
INCLUDE = [ADir("."), ADir("backend"), ADir("interface")]
ext_components_path = os.environ.get("EXT_COMPONENTS_PATH")
if ext_components_path:
    INCLUDE += [os.path.join(ext_components_path, "cp0_lvgl", "include")]
INCLUDE += [ADir("include")]
PRIVATE_INCLUDE = []
REQUIREMENTS = ["cp0_lvgl", "eventpp", "lvgl_component", "pthread", "ssl", "crypto", "utilities", "hv"]
STATIC_LIB = []
DYNAMIC_LIB = []
DEFINITIONS = []
DEFINITIONS_PRIVATE = []
LDFLAGS = []
LINK_SEARCH_PATH = []
STATIC_FILES = []
FREETYPE_INCLUDE = None
MULTIARCH_INCLUDE = None
SYSROOT_COMPONENT_INCLUDES = []

PROJECT_ROOT = os.path.abspath(os.path.join(os.getcwd(), ".."))
APPSTORE_STATIC_ROOT = os.path.join(PROJECT_ROOT, "APPLaunch")
APPLAUNCH_STATIC_ROOT = os.path.abspath(
    os.environ.get(
        "CARDPUTERZERO_APPLAUNCH_STATIC_ROOT",
        os.path.join(PROJECT_ROOT, "..", "APPLaunch", "APPLaunch"),
    )
)
STAGED_STATIC_ROOT = os.path.abspath(os.path.join("build", "static"))
STAGED_APPLAUNCH = os.path.join(STAGED_STATIC_ROOT, "APPLaunch")


def stage_appstore_static_files():
    if os.path.exists(STAGED_APPLAUNCH):
        shutil.rmtree(STAGED_APPLAUNCH)
    shutil.copytree(APPSTORE_STATIC_ROOT, STAGED_APPLAUNCH)
    status_images = [
        "status_ethernet.png",
        "status_time_background.png",
        "status_battery_background.png",
    ]
    dst_images = os.path.join(STAGED_APPLAUNCH, "share", "images")
    os.makedirs(dst_images, exist_ok=True)
    for image in status_images:
        shutil.copy2(
            os.path.join(APPLAUNCH_STATIC_ROOT, "share", "images", image),
            os.path.join(dst_images, image),
        )


stage_appstore_static_files()
STATIC_FILES += [STAGED_APPLAUNCH]

def pkg_config_flags(kind, package):
    try:
        return shlex.split(subprocess.check_output(["pkg-config", kind, package], text=True))
    except Exception:
        return []


def append_pkg_config(package, definitions, requirements, link_search_path, ldflags):
    for flag in pkg_config_flags("--cflags", package):
        definitions.append(flag)
    for flag in pkg_config_flags("--libs", package):
        if flag.startswith("-L"):
            link_search_path.append(flag[2:])
        elif flag.startswith("-l"):
            requirements.append(flag[2:])
        else:
            ldflags.append(flag)

static_sysroot = os.environ.get("CARDPUTERZERO_STATIC_LIB_SYSROOT") or os.environ.get("CONFIG_TOOLCHAIN_SYSROOT")
if static_sysroot:
    sysroot = static_sysroot.strip('"')
    multiarch_include = os.path.join(sysroot, "usr", "include", "aarch64-linux-gnu")
    if os.path.isdir(multiarch_include):
        INCLUDE += [multiarch_include]
        MULTIARCH_INCLUDE = multiarch_include
        SYSROOT_COMPONENT_INCLUDES.append(multiarch_include)
    for relative_include in (
        "usr/lib/aarch64-linux-gnu/dbus-1.0/include",
        "usr/lib/aarch64-linux-gnu/glib-2.0/include",
    ):
        component_include = os.path.join(sysroot, relative_include)
        if os.path.isdir(component_include):
            INCLUDE += [component_include]
            SYSROOT_COMPONENT_INCLUDES.append(component_include)
    freetype_include = os.path.join(sysroot, "usr", "include", "freetype2")
    if os.path.isdir(freetype_include):
        INCLUDE += [freetype_include]
        FREETYPE_INCLUDE = freetype_include
    multiarch_lib = os.path.join(sysroot, "usr", "lib", "aarch64-linux-gnu")
    if os.path.isdir(multiarch_lib):
        LDFLAGS += [
            f"--sysroot={sysroot}",
            f"-B{multiarch_lib}",
            f"-Wl,-rpath-link,{multiarch_lib}",
            f"{multiarch_lib}/libstdc++.so.6",
        ]
        LINK_SEARCH_PATH += [multiarch_lib]

lvgl_component = list(filter(lambda x: x["target"] == "lvgl_component", env["COMPONENTS"]))[0]
if FREETYPE_INCLUDE:
    for component in env["COMPONENTS"]:
        component["INCLUDE"] += [FREETYPE_INCLUDE]
if SYSROOT_COMPONENT_INCLUDES:
    for component in env["COMPONENTS"]:
        component["INCLUDE"] += SYSROOT_COMPONENT_INCLUDES
if "CONFIG_V9_5_LV_USE_FREETYPE" in os.environ:
    REQUIREMENTS += ["freetype"]
if "CONFIG_V9_5_LV_USE_SDL" in os.environ:
    lvgl_component["REQUIREMENTS"] += ["SDL2"]
    lvgl_component["INCLUDE"] += ["/usr/include/SDL2"]
    for sdl_include in [
        "/opt/homebrew/include",
        "/opt/homebrew/include/SDL2",
        "/usr/local/include",
        "/usr/local/include/SDL2",
    ]:
        if os.path.exists(sdl_include):
            lvgl_component["INCLUDE"] += [sdl_include]
    for sdl_lib in ["/opt/homebrew/lib", "/usr/local/lib"]:
        if os.path.exists(sdl_lib):
            lvgl_component["LINK_SEARCH_PATH"] += [sdl_lib]
    lvgl_component["DEFINITIONS"] += ["-D_REENTRANT"]
    append_pkg_config("freetype2", lvgl_component["DEFINITIONS"], REQUIREMENTS,
                      LINK_SEARCH_PATH, LDFLAGS)
    for src in list(lvgl_component["SRCS"]):
        if "lv_sdl_keyboard.c" in str(src):
            lvgl_component["SRCS"].remove(src)

env["COMPONENTS"].append(
    {
        "target": "M5CardputerZero-AppStore",
        "SRCS": SRCS,
        "INCLUDE": INCLUDE,
        "PRIVATE_INCLUDE": PRIVATE_INCLUDE,
        "REQUIREMENTS": REQUIREMENTS,
        "STATIC_LIB": STATIC_LIB,
        "DYNAMIC_LIB": DYNAMIC_LIB,
        "DEFINITIONS": DEFINITIONS,
        "DEFINITIONS_PRIVATE": DEFINITIONS_PRIVATE,
        "LDFLAGS": LDFLAGS,
        "LINK_SEARCH_PATH": LINK_SEARCH_PATH,
        "STATIC_FILES": STATIC_FILES,
        "REGISTER": "project",
    }
)
